### ISSUE TITLE
Collaboration with regulatory agencies

### ISSUE THREAD

**Issue by sureshkrishnan** [marisolpalmero/GREEN-bof#17]
I am unable to see how an eventual working group collaborates with regulatory agencies other than simply taking the regulatory background into consideration while working on solutions. Maybe worth clarifying this a bit.

**Comment by billwuqin** [comment]
I think we could influence European Commision regulation through interacting with ETSI EC EE, see ETSI EC EE activity report:
https://www.etsi.org/committee-activity/activity-report-ee
since ETSI EC EE has already be listed one liaison target in the charter text.
Also based on my observation, European Commission has set strict energy saving requirements for European Operators through CSRD and ESRS E1 climate changes. But not sure we should expand the scope of charter text to explore more about this direction.

**Comment by dhruvdhody** [comment]
+1 to Suresh, it is not something that we can actually do! Let's leave it out...

**Comment by tony1athome** [comment]
If we need to liase with other SDOs, that should be in the charter. If we are playing politics with regulators, that seems like it is more appropriate for e-impact.

**Comment by marisolpalmero** [comment]
removing from the charter the bullet point under the collaboration (*Dependencies and Liaisons):
   - Industry stakeholders and regulatory bodies to ensure alignment with current and future regulatory frameworks.
