### ISSUE TITLE
Charter -- Goals and Scope

### ISSUE THREAD

**Issue by cpignata** [marisolpalmero/GREEN-bof#25]
In regards to these 2 bullet points:

1. A framework that will enable the collection, aggregation and consumption for mentioned metrics and attributes developed in the WG.
2. A framework to enable incremental deployment by mapping legacy metrics, sourced from either dynamic or static data, to the new YANG models developed by the WG.

For 1., I am concerned that a single framework might overly constraint and leave outside important things, called in the IAB Workshop, such as _draft-pignataro-eimpact-icmp_

For 2., This is a vendor-specific translation at best, not something to be standardized. Static data?

**Comment by janlindblad** [comment]
It's a valid concern that a newly developed framework may preclude future data sources. I think it's key that the framework we choose or develop can incorporate data from a great variety of sources and mechanisms. It is important to have a single framework so that all the sources can combine and meet, however. I definitely think input from ICMP metric collection should be (made) possible, or else it's not a very good framework. Whether such an ICMP mechanism is defined day 1 or day 2 is not important for this point to be true.

Not sure what the meaning of the second concern is. What is vendor-specific? 

I believe static data refers to data that could be read from published data sheets, e.g. the maximum or "typical" power draw of a particular device.

**Comment by cpignata** [comment]
Thanks @janlindblad for this note.

Regarding the first concern, it seems the charter has already a very specific solution in mind. Capturing of the same metrics through other means needs to be explicitly allowed (as an option)

Regarding the second concern, my assumption was that "legacy" is "vendor specific" by definition... There is really no thing as "typical" power draw, as there's not way there's a normalization on that typical across BEs, vendors, etc., and frankly no archetypical single customer.

**Comment by marisolpalmero** [comment]
refer to issue #55
