### ISSUE TITLE
Charter -- Energy-Aware and Sustainability are not the same

### ISSUE THREAD

**Issue by cpignata** [marisolpalmero/GREEN-bof#51]
@marisolpalmero, it seems you Closed issue #21 without checking if your proposal actually addresses the issue...
I think it does not -- and since I cannot re-open the Issue, opening a new one :-| 

Is "Energy-Aware Networking" an existing term? If so citation.
If not, the definition that is included does not work.

**Comment by billwuqin** [comment]
I think we should use energy efficiency networking or energy efficiency network management since not only we can collect and report power, energy information, but also we can collect and report traffic information such as throughput, in addition, many device can directly report energy effiency ratio.
So I think the big shift for energy mangement is shift from energy consumption toward energy effiency improvement.

**Comment by cpignata** [comment]
Whichever the name, I’d suggest it be inclusive of what it is, and exclusive of what it’s not. If it is Energy Efficiency, then any other sustainability is out. EMAN is taken 😊 Is the focus of this effort energy optimization? Why is the list called “green-bof”?Thumb typed by Carlos Pignataro.Excuze typofraphicak errowsOn May 15, 2024, at 02:55, Qin Wu ***@***.***> wrote:﻿
I think we should use energy efficiency networking or energy efficiency network management since not only we can collect and report power, energy information, but also we can collect and report traffic information such as throughput, in addition, many device can directly report energy effiency ratio.
So I think the big shift for energy mangement is shift from energy consumption toward energy effiency improvement.

**Comment by marisolpalmero** [comment]
No Energy Aware in the text, it has been changed to "Energy efficiency"
