### ISSUE TITLE
Up-leveling the out-of-scope list

### ISSUE THREAD

**Issue by jariarkko** [marisolpalmero/GREEN-bof#6]
Great that we have an out-of-scope list!

I'd like to up-level it a bit though. Currently it feels very specific, as if some very specific proposals are ruled out and for specific reasons. And maybe we are doing that. But as a charter text, it would be perhaps easier to present some broader categories of out-of-scope topics and not go into the details of why the specific ones are out of scope. 

Suggested change below:

OLD:

- At this time, routing protocols and energy aware routing algorithms considering green energy factors are far from mature and are not in scope for this WG.
- Benchmarking methodology for power consumption in networking devices belongs in the BMWG, and is not in scope for this WG.
- Specification of green-oriented Network Quality Analysis (NQA) techniques to understand the impact of energy efficiency optimization on service quality, such as ICMP extensions for collection of environmental information.
- Regulatory Reporting, Compliance, and Corporate Responsibility Disclosure

NEW:

To stay focused, this working group will not address all issues. And some topics may already be covered elsewhere while others may not be mature enough or have unresolved security models. In any case, the following topics are not within the scope of the working group:

- Routing protocols and energy aware routing algorithms considering green energy factors
- Benchmarking methodology for power consumption in networking devices (a work item of the BMWG)
- Methodologies for understanding  the impact of energy efficiency optimization on service quality
- Inter-domain or consumer access to environmental information
- Regulatory, compliance, and corporate responsibility related matters

**Comment by raszuk** [comment]
I would recommend not to use term "Inter-domain" 

In IETF this means very specific interconnect topology which I am not sure if we want to rule out.

**Comment by marisolpalmero** [comment]
suggestion from Jari is committed.
TO BE DISCUSSED during May 13th call:
The still open question is that whether customer access to environment information can be listed, how do we understand inter-domain. 

note: inter-domain should be replaced by cross domain??

**Comment by luismcontreras** [comment]
As part of out-of-scope topics, but relevant for future work anywhere, I think it would be also convenient to add the determination of environmental impacts due to different traffic/service delivery strategies, such as e.g. infinite scroll. I mean, analyse what can be improved from the application side and how to integrate / interact with the network. 

This can be seen maybe as a complement to Jari's point on "Methodologies for understanding the impact of energy efficiency optimization on service quality".

**Comment by marisolpalmero** [comment]
@luismcontreras, will you consider it under methodology?

"Methodologies for understanding the environmental impact of energy efficiency optimisation on service quality, and traffic/service delivery strategies, e.g. infinite scroll"?

**Comment by luismcontreras** [comment]
Not actually. I think these are two complementary aspects: (1) "Methodologies for understanding the impact of energy efficiency optimization on service quality" which tries to determine the impact on services as consequence of the actions taken for optimizing energy efficiency in the network; and (2) "environmental impacts due to different traffic/service delivery strategies, such as e.g. infinite scroll" which tries to determine the consequences of different service strategies in the energy efficiency of the networks.
In my understanding are two different aspects.

**Comment by marisolpalmero** [comment]
@luismcontreras please could you suggest a proposal change?

**Comment by billwuqin** [comment]
I think we can close this open issue based on additional text in the out of scop section in the charter.
