### ISSUE TITLE
BOF Request Proposal - technology conflicts and overlaps

### ISSUE THREAD

**Issue by cpignata** [marisolpalmero/GREEN-bof#72]
Given
> The BoF discussion should identify a suite of short-term deliverables aimed at enhancing energy efficiency within networks,

Why the _Technology Overlap:_ include RTGWG, LSR, and do not include IVY?

Also, regarding
> Which (if any) modifications to existing protocols or practices are required:
> Approaches are likely to use Netconf/Restconf and YANG.
> Proposals to LSR for IGP enhancements for energy-efficient path computation.

Was that discussed as out-of-scope for an Ops not RTG proposal?

**Comment by billwuqin** [comment]
Based on earlier discussion and AD's guidelines, this proposed BOF is targeted to OPS area rather than routing area, for any routing protocol extension related work can be covered by another linked new BOF in Routing area, we can not boil ocean for the whole problem space. At least in the first phase, make sense?

**Comment by cpignata** [comment]
Makes sense -- so why is RTG as a conflict and not other Ops WGs?

**Comment by billwuqin** [comment]
The rationale is first, RTG is not in the scope since GREEN focuses on OPS area, secondly take IPPM, BMWG as examples, they will provide a good foundation or input to GREEN proposed work items while RTG is just consumer of these metrics.

**Comment by marisolpalmero** [comment]
no need to change proposal for the charter. Closing as per comments

**Comment by billwuqin** [comment]
Sorry, Carlos, I thought you are referred to Charter proposal, rather than BOF prposal.
Regarding your first comments, the answer is OPS area is referred to all WGs in the OPS area including IVY, does this make sense to you?
Regarding your second comments, Yes, you are right
here is the proposed change:
NEW TEXT:
"
Enhancements to IGPs and PCEP for energy-efficient path computation (not in the OPS WG scope).
"

**Comment by cpignata** [comment]
Thanks, even when responding to a **Closed** Issue...

If you include WG-level technologies, they you need to include IVY. Explicitly.
If you include Area-level, RTG and Ops can be a first approximation but you will need more details.

I suggest 
* Remove RTGWG, LSR and add IVY from Tech overlap
* add "Enhancements to IGPs and PCEP for energy-efficient path computation"
* Replace "OPS WG" with "OPSAWG"

And please update the BOF Proposal as it is confusing still.

Lastly, another mis-closed, @marisolpalmero
